### ISSUE TITLE
Add a test framework

### ISSUE THREAD

**Issue by d48** [matijaabicic/Moubot#13]
I recommend adding some unit test framework and start creating assertions on the src files in the repo. Look into https://www.npmjs.com/package/tape or https://www.npmjs.com/package/mocha

**Comment by matijaabicic** [comment]
Added Mocha, building tests as I go now.

**Comment by d48** [comment]
Awesome. I would add to the `.gitignore` file:

```
node_modules/
```

It's common to not include this directory in the git repo so that it doesn't bloat the project. People can do an `npm install` to download the dependencies in the `package.json` file

**Comment by matijaabicic** [comment]
Good point, thx!
